# AUTOMATICALLY GENERATED by `shtab`



complete pre-commit \
        'c/--/(all-files allow-missing-config bleeding-edge checkout-type color commit-msg-filename commit-object-name config files freeze from-ref help hook-dir hook-stage hook-type install-hooks is-squash-merge jobs local-branch no-allow-missing-config origin overwrite pre-rebase-branch pre-rebase-upstream prepare-commit-message-source print-completion ref remote-branch remote-name remote-url repo rev rewrite-command show-diff-on-failure skip-on-missing-config source to-ref verbose version)/' \
        'c/-/(- V a c f h j o s t v)/' \
        'n/-s/(bash zsh tcsh)/' \
        'n/--print-completion/(bash zsh tcsh)/' \
        'n/-t/(commit-msg post-checkout post-commit post-merge post-rewrite pre-commit pre-merge-commit pre-push pre-rebase prepare-commit-msg)/' \
        'n/--hook-type/(commit-msg post-checkout post-commit post-merge post-rewrite pre-commit pre-merge-commit pre-push pre-rebase prepare-commit-msg)/' \
        'n/-t/(commit-msg post-checkout post-commit post-merge post-rewrite pre-commit pre-merge-commit pre-push pre-rebase prepare-commit-msg)/' \
        'n/--hook-type/(commit-msg post-checkout post-commit post-merge post-rewrite pre-commit pre-merge-commit pre-push pre-rebase prepare-commit-msg)/' \
        'n/--hook-stage/(commit-msg post-checkout post-commit post-merge post-rewrite pre-commit pre-merge-commit pre-push pre-rebase prepare-commit-msg manual)/' \
        'n/--hook-stage/(commit-msg post-checkout post-commit post-merge post-rewrite pre-commit pre-merge-commit pre-push pre-rebase prepare-commit-msg manual)/' \
        'n/-t/(commit-msg post-checkout post-commit post-merge post-rewrite pre-commit pre-merge-commit pre-push pre-rebase prepare-commit-msg)/' \
        'n/--hook-type/(commit-msg post-checkout post-commit post-merge post-rewrite pre-commit pre-merge-commit pre-push pre-rebase prepare-commit-msg)/' \
        'p/1/(autoupdate clean gc init-templatedir install install-hooks migrate-config run sample-config try-repo uninstall validate-config validate-manifest help hook-impl)/' \
        'p@2@`set cmd=($COMMAND_LINE); `@' \
        'p/*/()/'
